include: package:lints/recommended.yaml

linter:
  rules:
    constant_identifier_names: false
    non_constant_identifier_names: false

analyzer:
  exclude:
    - "pigeons/*.dart"
    - "test/*.mocks.dart"
