// Autogenerated from Pigeon (v10.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "YMMFPigeon.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}
static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface YMMFAppMetricaConfigPigeon ()
+ (YMMFAppMetricaConfigPigeon *)fromList:(NSArray *)list;
+ (nullable YMMFAppMetricaConfigPigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface YMMFLocationPigeon ()
+ (YMMFLocationPigeon *)fromList:(NSArray *)list;
+ (nullable YMMFLocationPigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface YMMFPreloadInfoPigeon ()
+ (YMMFPreloadInfoPigeon *)fromList:(NSArray *)list;
+ (nullable YMMFPreloadInfoPigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface YMMFAppMetricaDeferredDeeplinkErrorPigeon ()
+ (YMMFAppMetricaDeferredDeeplinkErrorPigeon *)fromList:(NSArray *)list;
+ (nullable YMMFAppMetricaDeferredDeeplinkErrorPigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface YMMFAppMetricaDeferredDeeplinkPigeon ()
+ (YMMFAppMetricaDeferredDeeplinkPigeon *)fromList:(NSArray *)list;
+ (nullable YMMFAppMetricaDeferredDeeplinkPigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface YMMFAppMetricaDeferredDeeplinkParametersPigeon ()
+ (YMMFAppMetricaDeferredDeeplinkParametersPigeon *)fromList:(NSArray *)list;
+ (nullable YMMFAppMetricaDeferredDeeplinkParametersPigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface YMMFAppMetricaDeviceIdPigeon ()
+ (YMMFAppMetricaDeviceIdPigeon *)fromList:(NSArray *)list;
+ (nullable YMMFAppMetricaDeviceIdPigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface YMMFRevenuePigeon ()
+ (YMMFRevenuePigeon *)fromList:(NSArray *)list;
+ (nullable YMMFRevenuePigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface YMMFReceiptPigeon ()
+ (YMMFReceiptPigeon *)fromList:(NSArray *)list;
+ (nullable YMMFReceiptPigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface YMMFECommerceAmountPigeon ()
+ (YMMFECommerceAmountPigeon *)fromList:(NSArray *)list;
+ (nullable YMMFECommerceAmountPigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface YMMFECommerceProductPigeon ()
+ (YMMFECommerceProductPigeon *)fromList:(NSArray *)list;
+ (nullable YMMFECommerceProductPigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface YMMFECommercePricePigeon ()
+ (YMMFECommercePricePigeon *)fromList:(NSArray *)list;
+ (nullable YMMFECommercePricePigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface YMMFECommerceReferrerPigeon ()
+ (YMMFECommerceReferrerPigeon *)fromList:(NSArray *)list;
+ (nullable YMMFECommerceReferrerPigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface YMMFECommerceScreenPigeon ()
+ (YMMFECommerceScreenPigeon *)fromList:(NSArray *)list;
+ (nullable YMMFECommerceScreenPigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface YMMFECommerceCartItemPigeon ()
+ (YMMFECommerceCartItemPigeon *)fromList:(NSArray *)list;
+ (nullable YMMFECommerceCartItemPigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface YMMFECommerceOrderPigeon ()
+ (YMMFECommerceOrderPigeon *)fromList:(NSArray *)list;
+ (nullable YMMFECommerceOrderPigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface YMMFECommerceEventPigeon ()
+ (YMMFECommerceEventPigeon *)fromList:(NSArray *)list;
+ (nullable YMMFECommerceEventPigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface YMMFStackTraceElementPigeon ()
+ (YMMFStackTraceElementPigeon *)fromList:(NSArray *)list;
+ (nullable YMMFStackTraceElementPigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface YMMFErrorDetailsPigeon ()
+ (YMMFErrorDetailsPigeon *)fromList:(NSArray *)list;
+ (nullable YMMFErrorDetailsPigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface YMMFUserProfileAttributePigeon ()
+ (YMMFUserProfileAttributePigeon *)fromList:(NSArray *)list;
+ (nullable YMMFUserProfileAttributePigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface YMMFUserProfilePigeon ()
+ (YMMFUserProfilePigeon *)fromList:(NSArray *)list;
+ (nullable YMMFUserProfilePigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface YMMFAdRevenuePigeon ()
+ (YMMFAdRevenuePigeon *)fromList:(NSArray *)list;
+ (nullable YMMFAdRevenuePigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface YMMFReporterConfigPigeon ()
+ (YMMFReporterConfigPigeon *)fromList:(NSArray *)list;
+ (nullable YMMFReporterConfigPigeon *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation YMMFAppMetricaConfigPigeon
+ (instancetype)makeWithApiKey:(NSString *)apiKey
    appVersion:(nullable NSString *)appVersion
    crashReporting:(nullable NSNumber *)crashReporting
    firstActivationAsUpdate:(nullable NSNumber *)firstActivationAsUpdate
    location:(nullable YMMFLocationPigeon *)location
    locationTracking:(nullable NSNumber *)locationTracking
    logs:(nullable NSNumber *)logs
    sessionTimeout:(nullable NSNumber *)sessionTimeout
    statisticsSending:(nullable NSNumber *)statisticsSending
    preloadInfo:(nullable YMMFPreloadInfoPigeon *)preloadInfo
    maxReportsInDatabaseCount:(nullable NSNumber *)maxReportsInDatabaseCount
    nativeCrashReporting:(nullable NSNumber *)nativeCrashReporting
    sessionsAutoTracking:(nullable NSNumber *)sessionsAutoTracking
    errorEnvironment:(nullable NSDictionary<NSString *, NSString *> *)errorEnvironment
    userProfileID:(nullable NSString *)userProfileID
    revenueAutoTracking:(nullable NSNumber *)revenueAutoTracking
    appOpenTrackingEnabled:(nullable NSNumber *)appOpenTrackingEnabled {
  YMMFAppMetricaConfigPigeon* pigeonResult = [[YMMFAppMetricaConfigPigeon alloc] init];
  pigeonResult.apiKey = apiKey;
  pigeonResult.appVersion = appVersion;
  pigeonResult.crashReporting = crashReporting;
  pigeonResult.firstActivationAsUpdate = firstActivationAsUpdate;
  pigeonResult.location = location;
  pigeonResult.locationTracking = locationTracking;
  pigeonResult.logs = logs;
  pigeonResult.sessionTimeout = sessionTimeout;
  pigeonResult.statisticsSending = statisticsSending;
  pigeonResult.preloadInfo = preloadInfo;
  pigeonResult.maxReportsInDatabaseCount = maxReportsInDatabaseCount;
  pigeonResult.nativeCrashReporting = nativeCrashReporting;
  pigeonResult.sessionsAutoTracking = sessionsAutoTracking;
  pigeonResult.errorEnvironment = errorEnvironment;
  pigeonResult.userProfileID = userProfileID;
  pigeonResult.revenueAutoTracking = revenueAutoTracking;
  pigeonResult.appOpenTrackingEnabled = appOpenTrackingEnabled;
  return pigeonResult;
}
+ (YMMFAppMetricaConfigPigeon *)fromList:(NSArray *)list {
  YMMFAppMetricaConfigPigeon *pigeonResult = [[YMMFAppMetricaConfigPigeon alloc] init];
  pigeonResult.apiKey = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.apiKey != nil, @"");
  pigeonResult.appVersion = GetNullableObjectAtIndex(list, 1);
  pigeonResult.crashReporting = GetNullableObjectAtIndex(list, 2);
  pigeonResult.firstActivationAsUpdate = GetNullableObjectAtIndex(list, 3);
  pigeonResult.location = [YMMFLocationPigeon nullableFromList:(GetNullableObjectAtIndex(list, 4))];
  pigeonResult.locationTracking = GetNullableObjectAtIndex(list, 5);
  pigeonResult.logs = GetNullableObjectAtIndex(list, 6);
  pigeonResult.sessionTimeout = GetNullableObjectAtIndex(list, 7);
  pigeonResult.statisticsSending = GetNullableObjectAtIndex(list, 8);
  pigeonResult.preloadInfo = [YMMFPreloadInfoPigeon nullableFromList:(GetNullableObjectAtIndex(list, 9))];
  pigeonResult.maxReportsInDatabaseCount = GetNullableObjectAtIndex(list, 10);
  pigeonResult.nativeCrashReporting = GetNullableObjectAtIndex(list, 11);
  pigeonResult.sessionsAutoTracking = GetNullableObjectAtIndex(list, 12);
  pigeonResult.errorEnvironment = GetNullableObjectAtIndex(list, 13);
  pigeonResult.userProfileID = GetNullableObjectAtIndex(list, 14);
  pigeonResult.revenueAutoTracking = GetNullableObjectAtIndex(list, 15);
  pigeonResult.appOpenTrackingEnabled = GetNullableObjectAtIndex(list, 16);
  return pigeonResult;
}
+ (nullable YMMFAppMetricaConfigPigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFAppMetricaConfigPigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.apiKey ?: [NSNull null]),
    (self.appVersion ?: [NSNull null]),
    (self.crashReporting ?: [NSNull null]),
    (self.firstActivationAsUpdate ?: [NSNull null]),
    (self.location ? [self.location toList] : [NSNull null]),
    (self.locationTracking ?: [NSNull null]),
    (self.logs ?: [NSNull null]),
    (self.sessionTimeout ?: [NSNull null]),
    (self.statisticsSending ?: [NSNull null]),
    (self.preloadInfo ? [self.preloadInfo toList] : [NSNull null]),
    (self.maxReportsInDatabaseCount ?: [NSNull null]),
    (self.nativeCrashReporting ?: [NSNull null]),
    (self.sessionsAutoTracking ?: [NSNull null]),
    (self.errorEnvironment ?: [NSNull null]),
    (self.userProfileID ?: [NSNull null]),
    (self.revenueAutoTracking ?: [NSNull null]),
    (self.appOpenTrackingEnabled ?: [NSNull null]),
  ];
}
@end

@implementation YMMFLocationPigeon
+ (instancetype)makeWithLatitude:(NSNumber *)latitude
    longitude:(NSNumber *)longitude
    provider:(nullable NSString *)provider
    altitude:(nullable NSNumber *)altitude
    accuracy:(nullable NSNumber *)accuracy
    course:(nullable NSNumber *)course
    speed:(nullable NSNumber *)speed
    timestamp:(nullable NSNumber *)timestamp {
  YMMFLocationPigeon* pigeonResult = [[YMMFLocationPigeon alloc] init];
  pigeonResult.latitude = latitude;
  pigeonResult.longitude = longitude;
  pigeonResult.provider = provider;
  pigeonResult.altitude = altitude;
  pigeonResult.accuracy = accuracy;
  pigeonResult.course = course;
  pigeonResult.speed = speed;
  pigeonResult.timestamp = timestamp;
  return pigeonResult;
}
+ (YMMFLocationPigeon *)fromList:(NSArray *)list {
  YMMFLocationPigeon *pigeonResult = [[YMMFLocationPigeon alloc] init];
  pigeonResult.latitude = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.latitude != nil, @"");
  pigeonResult.longitude = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.longitude != nil, @"");
  pigeonResult.provider = GetNullableObjectAtIndex(list, 2);
  pigeonResult.altitude = GetNullableObjectAtIndex(list, 3);
  pigeonResult.accuracy = GetNullableObjectAtIndex(list, 4);
  pigeonResult.course = GetNullableObjectAtIndex(list, 5);
  pigeonResult.speed = GetNullableObjectAtIndex(list, 6);
  pigeonResult.timestamp = GetNullableObjectAtIndex(list, 7);
  return pigeonResult;
}
+ (nullable YMMFLocationPigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFLocationPigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.latitude ?: [NSNull null]),
    (self.longitude ?: [NSNull null]),
    (self.provider ?: [NSNull null]),
    (self.altitude ?: [NSNull null]),
    (self.accuracy ?: [NSNull null]),
    (self.course ?: [NSNull null]),
    (self.speed ?: [NSNull null]),
    (self.timestamp ?: [NSNull null]),
  ];
}
@end

@implementation YMMFPreloadInfoPigeon
+ (instancetype)makeWithTrackingId:(NSString *)trackingId
    additionalInfo:(nullable NSDictionary *)additionalInfo {
  YMMFPreloadInfoPigeon* pigeonResult = [[YMMFPreloadInfoPigeon alloc] init];
  pigeonResult.trackingId = trackingId;
  pigeonResult.additionalInfo = additionalInfo;
  return pigeonResult;
}
+ (YMMFPreloadInfoPigeon *)fromList:(NSArray *)list {
  YMMFPreloadInfoPigeon *pigeonResult = [[YMMFPreloadInfoPigeon alloc] init];
  pigeonResult.trackingId = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.trackingId != nil, @"");
  pigeonResult.additionalInfo = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable YMMFPreloadInfoPigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFPreloadInfoPigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.trackingId ?: [NSNull null]),
    (self.additionalInfo ?: [NSNull null]),
  ];
}
@end

@implementation YMMFAppMetricaDeferredDeeplinkErrorPigeon
+ (instancetype)makeWithReason:(YMMFAppMetricaDeferredDeeplinkReasonPigeon)reason
    description:(NSString *)description
    message:(nullable NSString *)message {
  YMMFAppMetricaDeferredDeeplinkErrorPigeon* pigeonResult = [[YMMFAppMetricaDeferredDeeplinkErrorPigeon alloc] init];
  pigeonResult.reason = reason;
  pigeonResult.description = description;
  pigeonResult.message = message;
  return pigeonResult;
}
+ (YMMFAppMetricaDeferredDeeplinkErrorPigeon *)fromList:(NSArray *)list {
  YMMFAppMetricaDeferredDeeplinkErrorPigeon *pigeonResult = [[YMMFAppMetricaDeferredDeeplinkErrorPigeon alloc] init];
  pigeonResult.reason = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.description = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.description != nil, @"");
  pigeonResult.message = GetNullableObjectAtIndex(list, 2);
  return pigeonResult;
}
+ (nullable YMMFAppMetricaDeferredDeeplinkErrorPigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFAppMetricaDeferredDeeplinkErrorPigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    @(self.reason),
    (self.description ?: [NSNull null]),
    (self.message ?: [NSNull null]),
  ];
}
@end

@implementation YMMFAppMetricaDeferredDeeplinkPigeon
+ (instancetype)makeWithDeeplink:(nullable NSString *)deeplink
    error:(nullable YMMFAppMetricaDeferredDeeplinkErrorPigeon *)error {
  YMMFAppMetricaDeferredDeeplinkPigeon* pigeonResult = [[YMMFAppMetricaDeferredDeeplinkPigeon alloc] init];
  pigeonResult.deeplink = deeplink;
  pigeonResult.error = error;
  return pigeonResult;
}
+ (YMMFAppMetricaDeferredDeeplinkPigeon *)fromList:(NSArray *)list {
  YMMFAppMetricaDeferredDeeplinkPigeon *pigeonResult = [[YMMFAppMetricaDeferredDeeplinkPigeon alloc] init];
  pigeonResult.deeplink = GetNullableObjectAtIndex(list, 0);
  pigeonResult.error = [YMMFAppMetricaDeferredDeeplinkErrorPigeon nullableFromList:(GetNullableObjectAtIndex(list, 1))];
  return pigeonResult;
}
+ (nullable YMMFAppMetricaDeferredDeeplinkPigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFAppMetricaDeferredDeeplinkPigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.deeplink ?: [NSNull null]),
    (self.error ? [self.error toList] : [NSNull null]),
  ];
}
@end

@implementation YMMFAppMetricaDeferredDeeplinkParametersPigeon
+ (instancetype)makeWithParameters:(nullable NSDictionary *)parameters
    error:(nullable YMMFAppMetricaDeferredDeeplinkErrorPigeon *)error {
  YMMFAppMetricaDeferredDeeplinkParametersPigeon* pigeonResult = [[YMMFAppMetricaDeferredDeeplinkParametersPigeon alloc] init];
  pigeonResult.parameters = parameters;
  pigeonResult.error = error;
  return pigeonResult;
}
+ (YMMFAppMetricaDeferredDeeplinkParametersPigeon *)fromList:(NSArray *)list {
  YMMFAppMetricaDeferredDeeplinkParametersPigeon *pigeonResult = [[YMMFAppMetricaDeferredDeeplinkParametersPigeon alloc] init];
  pigeonResult.parameters = GetNullableObjectAtIndex(list, 0);
  pigeonResult.error = [YMMFAppMetricaDeferredDeeplinkErrorPigeon nullableFromList:(GetNullableObjectAtIndex(list, 1))];
  return pigeonResult;
}
+ (nullable YMMFAppMetricaDeferredDeeplinkParametersPigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFAppMetricaDeferredDeeplinkParametersPigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.parameters ?: [NSNull null]),
    (self.error ? [self.error toList] : [NSNull null]),
  ];
}
@end

@implementation YMMFAppMetricaDeviceIdPigeon
+ (instancetype)makeWithDeviceId:(nullable NSString *)deviceId
    errorReason:(YMMFAppMetricaDeviceIdReasonPigeon)errorReason {
  YMMFAppMetricaDeviceIdPigeon* pigeonResult = [[YMMFAppMetricaDeviceIdPigeon alloc] init];
  pigeonResult.deviceId = deviceId;
  pigeonResult.errorReason = errorReason;
  return pigeonResult;
}
+ (YMMFAppMetricaDeviceIdPigeon *)fromList:(NSArray *)list {
  YMMFAppMetricaDeviceIdPigeon *pigeonResult = [[YMMFAppMetricaDeviceIdPigeon alloc] init];
  pigeonResult.deviceId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.errorReason = [GetNullableObjectAtIndex(list, 1) integerValue];
  return pigeonResult;
}
+ (nullable YMMFAppMetricaDeviceIdPigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFAppMetricaDeviceIdPigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.deviceId ?: [NSNull null]),
    @(self.errorReason),
  ];
}
@end

@implementation YMMFRevenuePigeon
+ (instancetype)makeWithPrice:(NSString *)price
    currency:(NSString *)currency
    quantity:(nullable NSNumber *)quantity
    productId:(nullable NSString *)productId
    payload:(nullable NSString *)payload
    receipt:(nullable YMMFReceiptPigeon *)receipt
    transactionId:(nullable NSString *)transactionId {
  YMMFRevenuePigeon* pigeonResult = [[YMMFRevenuePigeon alloc] init];
  pigeonResult.price = price;
  pigeonResult.currency = currency;
  pigeonResult.quantity = quantity;
  pigeonResult.productId = productId;
  pigeonResult.payload = payload;
  pigeonResult.receipt = receipt;
  pigeonResult.transactionId = transactionId;
  return pigeonResult;
}
+ (YMMFRevenuePigeon *)fromList:(NSArray *)list {
  YMMFRevenuePigeon *pigeonResult = [[YMMFRevenuePigeon alloc] init];
  pigeonResult.price = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.price != nil, @"");
  pigeonResult.currency = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.currency != nil, @"");
  pigeonResult.quantity = GetNullableObjectAtIndex(list, 2);
  pigeonResult.productId = GetNullableObjectAtIndex(list, 3);
  pigeonResult.payload = GetNullableObjectAtIndex(list, 4);
  pigeonResult.receipt = [YMMFReceiptPigeon nullableFromList:(GetNullableObjectAtIndex(list, 5))];
  pigeonResult.transactionId = GetNullableObjectAtIndex(list, 6);
  return pigeonResult;
}
+ (nullable YMMFRevenuePigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFRevenuePigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.price ?: [NSNull null]),
    (self.currency ?: [NSNull null]),
    (self.quantity ?: [NSNull null]),
    (self.productId ?: [NSNull null]),
    (self.payload ?: [NSNull null]),
    (self.receipt ? [self.receipt toList] : [NSNull null]),
    (self.transactionId ?: [NSNull null]),
  ];
}
@end

@implementation YMMFReceiptPigeon
+ (instancetype)makeWithData:(nullable NSString *)data
    signature:(nullable NSString *)signature {
  YMMFReceiptPigeon* pigeonResult = [[YMMFReceiptPigeon alloc] init];
  pigeonResult.data = data;
  pigeonResult.signature = signature;
  return pigeonResult;
}
+ (YMMFReceiptPigeon *)fromList:(NSArray *)list {
  YMMFReceiptPigeon *pigeonResult = [[YMMFReceiptPigeon alloc] init];
  pigeonResult.data = GetNullableObjectAtIndex(list, 0);
  pigeonResult.signature = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable YMMFReceiptPigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFReceiptPigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.data ?: [NSNull null]),
    (self.signature ?: [NSNull null]),
  ];
}
@end

@implementation YMMFECommerceAmountPigeon
+ (instancetype)makeWithAmount:(NSString *)amount
    currency:(NSString *)currency {
  YMMFECommerceAmountPigeon* pigeonResult = [[YMMFECommerceAmountPigeon alloc] init];
  pigeonResult.amount = amount;
  pigeonResult.currency = currency;
  return pigeonResult;
}
+ (YMMFECommerceAmountPigeon *)fromList:(NSArray *)list {
  YMMFECommerceAmountPigeon *pigeonResult = [[YMMFECommerceAmountPigeon alloc] init];
  pigeonResult.amount = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.amount != nil, @"");
  pigeonResult.currency = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.currency != nil, @"");
  return pigeonResult;
}
+ (nullable YMMFECommerceAmountPigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFECommerceAmountPigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.amount ?: [NSNull null]),
    (self.currency ?: [NSNull null]),
  ];
}
@end

@implementation YMMFECommerceProductPigeon
+ (instancetype)makeWithSku:(NSString *)sku
    name:(nullable NSString *)name
    categoriesPath:(nullable NSArray<NSString *> *)categoriesPath
    payload:(nullable NSDictionary<NSString *, NSString *> *)payload
    actualPrice:(nullable YMMFECommercePricePigeon *)actualPrice
    originalPrice:(nullable YMMFECommercePricePigeon *)originalPrice
    promocodes:(nullable NSArray<NSString *> *)promocodes {
  YMMFECommerceProductPigeon* pigeonResult = [[YMMFECommerceProductPigeon alloc] init];
  pigeonResult.sku = sku;
  pigeonResult.name = name;
  pigeonResult.categoriesPath = categoriesPath;
  pigeonResult.payload = payload;
  pigeonResult.actualPrice = actualPrice;
  pigeonResult.originalPrice = originalPrice;
  pigeonResult.promocodes = promocodes;
  return pigeonResult;
}
+ (YMMFECommerceProductPigeon *)fromList:(NSArray *)list {
  YMMFECommerceProductPigeon *pigeonResult = [[YMMFECommerceProductPigeon alloc] init];
  pigeonResult.sku = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.sku != nil, @"");
  pigeonResult.name = GetNullableObjectAtIndex(list, 1);
  pigeonResult.categoriesPath = GetNullableObjectAtIndex(list, 2);
  pigeonResult.payload = GetNullableObjectAtIndex(list, 3);
  pigeonResult.actualPrice = [YMMFECommercePricePigeon nullableFromList:(GetNullableObjectAtIndex(list, 4))];
  pigeonResult.originalPrice = [YMMFECommercePricePigeon nullableFromList:(GetNullableObjectAtIndex(list, 5))];
  pigeonResult.promocodes = GetNullableObjectAtIndex(list, 6);
  return pigeonResult;
}
+ (nullable YMMFECommerceProductPigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFECommerceProductPigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.sku ?: [NSNull null]),
    (self.name ?: [NSNull null]),
    (self.categoriesPath ?: [NSNull null]),
    (self.payload ?: [NSNull null]),
    (self.actualPrice ? [self.actualPrice toList] : [NSNull null]),
    (self.originalPrice ? [self.originalPrice toList] : [NSNull null]),
    (self.promocodes ?: [NSNull null]),
  ];
}
@end

@implementation YMMFECommercePricePigeon
+ (instancetype)makeWithFiat:(YMMFECommerceAmountPigeon *)fiat
    internalComponents:(nullable NSArray<YMMFECommerceAmountPigeon *> *)internalComponents {
  YMMFECommercePricePigeon* pigeonResult = [[YMMFECommercePricePigeon alloc] init];
  pigeonResult.fiat = fiat;
  pigeonResult.internalComponents = internalComponents;
  return pigeonResult;
}
+ (YMMFECommercePricePigeon *)fromList:(NSArray *)list {
  YMMFECommercePricePigeon *pigeonResult = [[YMMFECommercePricePigeon alloc] init];
  pigeonResult.fiat = [YMMFECommerceAmountPigeon nullableFromList:(GetNullableObjectAtIndex(list, 0))];
  NSAssert(pigeonResult.fiat != nil, @"");
  pigeonResult.internalComponents = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable YMMFECommercePricePigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFECommercePricePigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.fiat ? [self.fiat toList] : [NSNull null]),
    (self.internalComponents ?: [NSNull null]),
  ];
}
@end

@implementation YMMFECommerceReferrerPigeon
+ (instancetype)makeWithType:(nullable NSString *)type
    identifier:(nullable NSString *)identifier
    screen:(nullable YMMFECommerceScreenPigeon *)screen {
  YMMFECommerceReferrerPigeon* pigeonResult = [[YMMFECommerceReferrerPigeon alloc] init];
  pigeonResult.type = type;
  pigeonResult.identifier = identifier;
  pigeonResult.screen = screen;
  return pigeonResult;
}
+ (YMMFECommerceReferrerPigeon *)fromList:(NSArray *)list {
  YMMFECommerceReferrerPigeon *pigeonResult = [[YMMFECommerceReferrerPigeon alloc] init];
  pigeonResult.type = GetNullableObjectAtIndex(list, 0);
  pigeonResult.identifier = GetNullableObjectAtIndex(list, 1);
  pigeonResult.screen = [YMMFECommerceScreenPigeon nullableFromList:(GetNullableObjectAtIndex(list, 2))];
  return pigeonResult;
}
+ (nullable YMMFECommerceReferrerPigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFECommerceReferrerPigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.type ?: [NSNull null]),
    (self.identifier ?: [NSNull null]),
    (self.screen ? [self.screen toList] : [NSNull null]),
  ];
}
@end

@implementation YMMFECommerceScreenPigeon
+ (instancetype)makeWithName:(nullable NSString *)name
    categoriesPath:(nullable NSArray<NSString *> *)categoriesPath
    searchQuery:(nullable NSString *)searchQuery
    payload:(nullable NSDictionary<NSString *, NSString *> *)payload {
  YMMFECommerceScreenPigeon* pigeonResult = [[YMMFECommerceScreenPigeon alloc] init];
  pigeonResult.name = name;
  pigeonResult.categoriesPath = categoriesPath;
  pigeonResult.searchQuery = searchQuery;
  pigeonResult.payload = payload;
  return pigeonResult;
}
+ (YMMFECommerceScreenPigeon *)fromList:(NSArray *)list {
  YMMFECommerceScreenPigeon *pigeonResult = [[YMMFECommerceScreenPigeon alloc] init];
  pigeonResult.name = GetNullableObjectAtIndex(list, 0);
  pigeonResult.categoriesPath = GetNullableObjectAtIndex(list, 1);
  pigeonResult.searchQuery = GetNullableObjectAtIndex(list, 2);
  pigeonResult.payload = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable YMMFECommerceScreenPigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFECommerceScreenPigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.name ?: [NSNull null]),
    (self.categoriesPath ?: [NSNull null]),
    (self.searchQuery ?: [NSNull null]),
    (self.payload ?: [NSNull null]),
  ];
}
@end

@implementation YMMFECommerceCartItemPigeon
+ (instancetype)makeWithProduct:(YMMFECommerceProductPigeon *)product
    quantity:(NSString *)quantity
    revenue:(YMMFECommercePricePigeon *)revenue
    referrer:(nullable YMMFECommerceReferrerPigeon *)referrer {
  YMMFECommerceCartItemPigeon* pigeonResult = [[YMMFECommerceCartItemPigeon alloc] init];
  pigeonResult.product = product;
  pigeonResult.quantity = quantity;
  pigeonResult.revenue = revenue;
  pigeonResult.referrer = referrer;
  return pigeonResult;
}
+ (YMMFECommerceCartItemPigeon *)fromList:(NSArray *)list {
  YMMFECommerceCartItemPigeon *pigeonResult = [[YMMFECommerceCartItemPigeon alloc] init];
  pigeonResult.product = [YMMFECommerceProductPigeon nullableFromList:(GetNullableObjectAtIndex(list, 0))];
  NSAssert(pigeonResult.product != nil, @"");
  pigeonResult.quantity = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.quantity != nil, @"");
  pigeonResult.revenue = [YMMFECommercePricePigeon nullableFromList:(GetNullableObjectAtIndex(list, 2))];
  NSAssert(pigeonResult.revenue != nil, @"");
  pigeonResult.referrer = [YMMFECommerceReferrerPigeon nullableFromList:(GetNullableObjectAtIndex(list, 3))];
  return pigeonResult;
}
+ (nullable YMMFECommerceCartItemPigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFECommerceCartItemPigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.product ? [self.product toList] : [NSNull null]),
    (self.quantity ?: [NSNull null]),
    (self.revenue ? [self.revenue toList] : [NSNull null]),
    (self.referrer ? [self.referrer toList] : [NSNull null]),
  ];
}
@end

@implementation YMMFECommerceOrderPigeon
+ (instancetype)makeWithIdentifier:(NSString *)identifier
    items:(NSArray<YMMFECommerceCartItemPigeon *> *)items
    payload:(nullable NSDictionary<NSString *, NSString *> *)payload {
  YMMFECommerceOrderPigeon* pigeonResult = [[YMMFECommerceOrderPigeon alloc] init];
  pigeonResult.identifier = identifier;
  pigeonResult.items = items;
  pigeonResult.payload = payload;
  return pigeonResult;
}
+ (YMMFECommerceOrderPigeon *)fromList:(NSArray *)list {
  YMMFECommerceOrderPigeon *pigeonResult = [[YMMFECommerceOrderPigeon alloc] init];
  pigeonResult.identifier = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.identifier != nil, @"");
  pigeonResult.items = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.items != nil, @"");
  pigeonResult.payload = GetNullableObjectAtIndex(list, 2);
  return pigeonResult;
}
+ (nullable YMMFECommerceOrderPigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFECommerceOrderPigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.identifier ?: [NSNull null]),
    (self.items ?: [NSNull null]),
    (self.payload ?: [NSNull null]),
  ];
}
@end

@implementation YMMFECommerceEventPigeon
+ (instancetype)makeWithEventType:(NSString *)eventType
    cartItem:(nullable YMMFECommerceCartItemPigeon *)cartItem
    order:(nullable YMMFECommerceOrderPigeon *)order
    product:(nullable YMMFECommerceProductPigeon *)product
    referrer:(nullable YMMFECommerceReferrerPigeon *)referrer
    screen:(nullable YMMFECommerceScreenPigeon *)screen {
  YMMFECommerceEventPigeon* pigeonResult = [[YMMFECommerceEventPigeon alloc] init];
  pigeonResult.eventType = eventType;
  pigeonResult.cartItem = cartItem;
  pigeonResult.order = order;
  pigeonResult.product = product;
  pigeonResult.referrer = referrer;
  pigeonResult.screen = screen;
  return pigeonResult;
}
+ (YMMFECommerceEventPigeon *)fromList:(NSArray *)list {
  YMMFECommerceEventPigeon *pigeonResult = [[YMMFECommerceEventPigeon alloc] init];
  pigeonResult.eventType = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.eventType != nil, @"");
  pigeonResult.cartItem = [YMMFECommerceCartItemPigeon nullableFromList:(GetNullableObjectAtIndex(list, 1))];
  pigeonResult.order = [YMMFECommerceOrderPigeon nullableFromList:(GetNullableObjectAtIndex(list, 2))];
  pigeonResult.product = [YMMFECommerceProductPigeon nullableFromList:(GetNullableObjectAtIndex(list, 3))];
  pigeonResult.referrer = [YMMFECommerceReferrerPigeon nullableFromList:(GetNullableObjectAtIndex(list, 4))];
  pigeonResult.screen = [YMMFECommerceScreenPigeon nullableFromList:(GetNullableObjectAtIndex(list, 5))];
  return pigeonResult;
}
+ (nullable YMMFECommerceEventPigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFECommerceEventPigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.eventType ?: [NSNull null]),
    (self.cartItem ? [self.cartItem toList] : [NSNull null]),
    (self.order ? [self.order toList] : [NSNull null]),
    (self.product ? [self.product toList] : [NSNull null]),
    (self.referrer ? [self.referrer toList] : [NSNull null]),
    (self.screen ? [self.screen toList] : [NSNull null]),
  ];
}
@end

@implementation YMMFStackTraceElementPigeon
+ (instancetype)makeWithClassName:(NSString *)className
    fileName:(nullable NSString *)fileName
    line:(NSNumber *)line
    column:(NSNumber *)column
    methodName:(NSString *)methodName {
  YMMFStackTraceElementPigeon* pigeonResult = [[YMMFStackTraceElementPigeon alloc] init];
  pigeonResult.className = className;
  pigeonResult.fileName = fileName;
  pigeonResult.line = line;
  pigeonResult.column = column;
  pigeonResult.methodName = methodName;
  return pigeonResult;
}
+ (YMMFStackTraceElementPigeon *)fromList:(NSArray *)list {
  YMMFStackTraceElementPigeon *pigeonResult = [[YMMFStackTraceElementPigeon alloc] init];
  pigeonResult.className = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.className != nil, @"");
  pigeonResult.fileName = GetNullableObjectAtIndex(list, 1);
  pigeonResult.line = GetNullableObjectAtIndex(list, 2);
  NSAssert(pigeonResult.line != nil, @"");
  pigeonResult.column = GetNullableObjectAtIndex(list, 3);
  NSAssert(pigeonResult.column != nil, @"");
  pigeonResult.methodName = GetNullableObjectAtIndex(list, 4);
  NSAssert(pigeonResult.methodName != nil, @"");
  return pigeonResult;
}
+ (nullable YMMFStackTraceElementPigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFStackTraceElementPigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.className ?: [NSNull null]),
    (self.fileName ?: [NSNull null]),
    (self.line ?: [NSNull null]),
    (self.column ?: [NSNull null]),
    (self.methodName ?: [NSNull null]),
  ];
}
@end

@implementation YMMFErrorDetailsPigeon
+ (instancetype)makeWithExceptionClass:(NSString *)exceptionClass
    message:(nullable NSString *)message
    dartVersion:(NSString *)dartVersion
    backtrace:(nullable NSArray<YMMFStackTraceElementPigeon *> *)backtrace {
  YMMFErrorDetailsPigeon* pigeonResult = [[YMMFErrorDetailsPigeon alloc] init];
  pigeonResult.exceptionClass = exceptionClass;
  pigeonResult.message = message;
  pigeonResult.dartVersion = dartVersion;
  pigeonResult.backtrace = backtrace;
  return pigeonResult;
}
+ (YMMFErrorDetailsPigeon *)fromList:(NSArray *)list {
  YMMFErrorDetailsPigeon *pigeonResult = [[YMMFErrorDetailsPigeon alloc] init];
  pigeonResult.exceptionClass = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.exceptionClass != nil, @"");
  pigeonResult.message = GetNullableObjectAtIndex(list, 1);
  pigeonResult.dartVersion = GetNullableObjectAtIndex(list, 2);
  NSAssert(pigeonResult.dartVersion != nil, @"");
  pigeonResult.backtrace = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable YMMFErrorDetailsPigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFErrorDetailsPigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.exceptionClass ?: [NSNull null]),
    (self.message ?: [NSNull null]),
    (self.dartVersion ?: [NSNull null]),
    (self.backtrace ?: [NSNull null]),
  ];
}
@end

@implementation YMMFUserProfileAttributePigeon
+ (instancetype)makeWithKey:(NSString *)key
    doubleValue:(nullable NSNumber *)doubleValue
    stringValue:(nullable NSString *)stringValue
    boolValue:(nullable NSNumber *)boolValue
    year:(nullable NSNumber *)year
    month:(nullable NSNumber *)month
    day:(nullable NSNumber *)day
    age:(nullable NSNumber *)age
    genderValue:(YMMFGenderPigeon)genderValue
    ifUndefined:(nullable NSNumber *)ifUndefined
    reset:(nullable NSNumber *)reset
    type:(YMMFUserProfileAttributeType)type {
  YMMFUserProfileAttributePigeon* pigeonResult = [[YMMFUserProfileAttributePigeon alloc] init];
  pigeonResult.key = key;
  pigeonResult.doubleValue = doubleValue;
  pigeonResult.stringValue = stringValue;
  pigeonResult.boolValue = boolValue;
  pigeonResult.year = year;
  pigeonResult.month = month;
  pigeonResult.day = day;
  pigeonResult.age = age;
  pigeonResult.genderValue = genderValue;
  pigeonResult.ifUndefined = ifUndefined;
  pigeonResult.reset = reset;
  pigeonResult.type = type;
  return pigeonResult;
}
+ (YMMFUserProfileAttributePigeon *)fromList:(NSArray *)list {
  YMMFUserProfileAttributePigeon *pigeonResult = [[YMMFUserProfileAttributePigeon alloc] init];
  pigeonResult.key = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.key != nil, @"");
  pigeonResult.doubleValue = GetNullableObjectAtIndex(list, 1);
  pigeonResult.stringValue = GetNullableObjectAtIndex(list, 2);
  pigeonResult.boolValue = GetNullableObjectAtIndex(list, 3);
  pigeonResult.year = GetNullableObjectAtIndex(list, 4);
  pigeonResult.month = GetNullableObjectAtIndex(list, 5);
  pigeonResult.day = GetNullableObjectAtIndex(list, 6);
  pigeonResult.age = GetNullableObjectAtIndex(list, 7);
  pigeonResult.genderValue = [GetNullableObjectAtIndex(list, 8) integerValue];
  pigeonResult.ifUndefined = GetNullableObjectAtIndex(list, 9);
  pigeonResult.reset = GetNullableObjectAtIndex(list, 10);
  pigeonResult.type = [GetNullableObjectAtIndex(list, 11) integerValue];
  return pigeonResult;
}
+ (nullable YMMFUserProfileAttributePigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFUserProfileAttributePigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.key ?: [NSNull null]),
    (self.doubleValue ?: [NSNull null]),
    (self.stringValue ?: [NSNull null]),
    (self.boolValue ?: [NSNull null]),
    (self.year ?: [NSNull null]),
    (self.month ?: [NSNull null]),
    (self.day ?: [NSNull null]),
    (self.age ?: [NSNull null]),
    @(self.genderValue),
    (self.ifUndefined ?: [NSNull null]),
    (self.reset ?: [NSNull null]),
    @(self.type),
  ];
}
@end

@implementation YMMFUserProfilePigeon
+ (instancetype)makeWithAttributes:(NSArray<YMMFUserProfileAttributePigeon *> *)attributes {
  YMMFUserProfilePigeon* pigeonResult = [[YMMFUserProfilePigeon alloc] init];
  pigeonResult.attributes = attributes;
  return pigeonResult;
}
+ (YMMFUserProfilePigeon *)fromList:(NSArray *)list {
  YMMFUserProfilePigeon *pigeonResult = [[YMMFUserProfilePigeon alloc] init];
  pigeonResult.attributes = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.attributes != nil, @"");
  return pigeonResult;
}
+ (nullable YMMFUserProfilePigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFUserProfilePigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.attributes ?: [NSNull null]),
  ];
}
@end

@implementation YMMFAdRevenuePigeon
+ (instancetype)makeWithAdRevenue:(NSString *)adRevenue
    currency:(NSString *)currency
    adType:(YMMFAdTypePigeon)adType
    adNetwork:(nullable NSString *)adNetwork
    adUnitId:(nullable NSString *)adUnitId
    adUnitName:(nullable NSString *)adUnitName
    adPlacementId:(nullable NSString *)adPlacementId
    adPlacementName:(nullable NSString *)adPlacementName
    precision:(nullable NSString *)precision
    payload:(nullable NSDictionary<NSString *, NSString *> *)payload {
  YMMFAdRevenuePigeon* pigeonResult = [[YMMFAdRevenuePigeon alloc] init];
  pigeonResult.adRevenue = adRevenue;
  pigeonResult.currency = currency;
  pigeonResult.adType = adType;
  pigeonResult.adNetwork = adNetwork;
  pigeonResult.adUnitId = adUnitId;
  pigeonResult.adUnitName = adUnitName;
  pigeonResult.adPlacementId = adPlacementId;
  pigeonResult.adPlacementName = adPlacementName;
  pigeonResult.precision = precision;
  pigeonResult.payload = payload;
  return pigeonResult;
}
+ (YMMFAdRevenuePigeon *)fromList:(NSArray *)list {
  YMMFAdRevenuePigeon *pigeonResult = [[YMMFAdRevenuePigeon alloc] init];
  pigeonResult.adRevenue = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.adRevenue != nil, @"");
  pigeonResult.currency = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.currency != nil, @"");
  pigeonResult.adType = [GetNullableObjectAtIndex(list, 2) integerValue];
  pigeonResult.adNetwork = GetNullableObjectAtIndex(list, 3);
  pigeonResult.adUnitId = GetNullableObjectAtIndex(list, 4);
  pigeonResult.adUnitName = GetNullableObjectAtIndex(list, 5);
  pigeonResult.adPlacementId = GetNullableObjectAtIndex(list, 6);
  pigeonResult.adPlacementName = GetNullableObjectAtIndex(list, 7);
  pigeonResult.precision = GetNullableObjectAtIndex(list, 8);
  pigeonResult.payload = GetNullableObjectAtIndex(list, 9);
  return pigeonResult;
}
+ (nullable YMMFAdRevenuePigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFAdRevenuePigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.adRevenue ?: [NSNull null]),
    (self.currency ?: [NSNull null]),
    @(self.adType),
    (self.adNetwork ?: [NSNull null]),
    (self.adUnitId ?: [NSNull null]),
    (self.adUnitName ?: [NSNull null]),
    (self.adPlacementId ?: [NSNull null]),
    (self.adPlacementName ?: [NSNull null]),
    (self.precision ?: [NSNull null]),
    (self.payload ?: [NSNull null]),
  ];
}
@end

@implementation YMMFReporterConfigPigeon
+ (instancetype)makeWithApiKey:(NSString *)apiKey
    sessionTimeout:(nullable NSNumber *)sessionTimeout
    statisticsSending:(nullable NSNumber *)statisticsSending
    maxReportsInDatabaseCount:(nullable NSNumber *)maxReportsInDatabaseCount
    userProfileID:(nullable NSString *)userProfileID
    logs:(nullable NSNumber *)logs {
  YMMFReporterConfigPigeon* pigeonResult = [[YMMFReporterConfigPigeon alloc] init];
  pigeonResult.apiKey = apiKey;
  pigeonResult.sessionTimeout = sessionTimeout;
  pigeonResult.statisticsSending = statisticsSending;
  pigeonResult.maxReportsInDatabaseCount = maxReportsInDatabaseCount;
  pigeonResult.userProfileID = userProfileID;
  pigeonResult.logs = logs;
  return pigeonResult;
}
+ (YMMFReporterConfigPigeon *)fromList:(NSArray *)list {
  YMMFReporterConfigPigeon *pigeonResult = [[YMMFReporterConfigPigeon alloc] init];
  pigeonResult.apiKey = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.apiKey != nil, @"");
  pigeonResult.sessionTimeout = GetNullableObjectAtIndex(list, 1);
  pigeonResult.statisticsSending = GetNullableObjectAtIndex(list, 2);
  pigeonResult.maxReportsInDatabaseCount = GetNullableObjectAtIndex(list, 3);
  pigeonResult.userProfileID = GetNullableObjectAtIndex(list, 4);
  pigeonResult.logs = GetNullableObjectAtIndex(list, 5);
  return pigeonResult;
}
+ (nullable YMMFReporterConfigPigeon *)nullableFromList:(NSArray *)list {
  return (list) ? [YMMFReporterConfigPigeon fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.apiKey ?: [NSNull null]),
    (self.sessionTimeout ?: [NSNull null]),
    (self.statisticsSending ?: [NSNull null]),
    (self.maxReportsInDatabaseCount ?: [NSNull null]),
    (self.userProfileID ?: [NSNull null]),
    (self.logs ?: [NSNull null]),
  ];
}
@end

@interface YMMFAppMetricaConfigConverterPigeonCodecReader : FlutterStandardReader
@end
@implementation YMMFAppMetricaConfigConverterPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [YMMFAppMetricaConfigPigeon fromList:[self readValue]];
    case 129: 
      return [YMMFLocationPigeon fromList:[self readValue]];
    case 130: 
      return [YMMFPreloadInfoPigeon fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface YMMFAppMetricaConfigConverterPigeonCodecWriter : FlutterStandardWriter
@end
@implementation YMMFAppMetricaConfigConverterPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[YMMFAppMetricaConfigPigeon class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFLocationPigeon class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFPreloadInfoPigeon class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface YMMFAppMetricaConfigConverterPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation YMMFAppMetricaConfigConverterPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[YMMFAppMetricaConfigConverterPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[YMMFAppMetricaConfigConverterPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *YMMFAppMetricaConfigConverterPigeonGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    YMMFAppMetricaConfigConverterPigeonCodecReaderWriter *readerWriter = [[YMMFAppMetricaConfigConverterPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void YMMFAppMetricaConfigConverterPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<YMMFAppMetricaConfigConverterPigeon> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaConfigConverterPigeon.toJson"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaConfigConverterPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(toJsonConfig:error:)], @"YMMFAppMetricaConfigConverterPigeon api (%@) doesn't respond to @selector(toJsonConfig:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        YMMFAppMetricaConfigPigeon *arg_config = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSString *output = [api toJsonConfig:arg_config error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface YMMFAppMetricaPigeonCodecReader : FlutterStandardReader
@end
@implementation YMMFAppMetricaPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [YMMFAdRevenuePigeon fromList:[self readValue]];
    case 129: 
      return [YMMFAppMetricaConfigPigeon fromList:[self readValue]];
    case 130: 
      return [YMMFAppMetricaDeferredDeeplinkErrorPigeon fromList:[self readValue]];
    case 131: 
      return [YMMFAppMetricaDeferredDeeplinkParametersPigeon fromList:[self readValue]];
    case 132: 
      return [YMMFAppMetricaDeferredDeeplinkPigeon fromList:[self readValue]];
    case 133: 
      return [YMMFAppMetricaDeviceIdPigeon fromList:[self readValue]];
    case 134: 
      return [YMMFECommerceAmountPigeon fromList:[self readValue]];
    case 135: 
      return [YMMFECommerceAmountPigeon fromList:[self readValue]];
    case 136: 
      return [YMMFECommerceCartItemPigeon fromList:[self readValue]];
    case 137: 
      return [YMMFECommerceEventPigeon fromList:[self readValue]];
    case 138: 
      return [YMMFECommerceOrderPigeon fromList:[self readValue]];
    case 139: 
      return [YMMFECommercePricePigeon fromList:[self readValue]];
    case 140: 
      return [YMMFECommercePricePigeon fromList:[self readValue]];
    case 141: 
      return [YMMFECommerceProductPigeon fromList:[self readValue]];
    case 142: 
      return [YMMFECommerceProductPigeon fromList:[self readValue]];
    case 143: 
      return [YMMFECommerceReferrerPigeon fromList:[self readValue]];
    case 144: 
      return [YMMFECommerceScreenPigeon fromList:[self readValue]];
    case 145: 
      return [YMMFErrorDetailsPigeon fromList:[self readValue]];
    case 146: 
      return [YMMFErrorDetailsPigeon fromList:[self readValue]];
    case 147: 
      return [YMMFLocationPigeon fromList:[self readValue]];
    case 148: 
      return [YMMFPreloadInfoPigeon fromList:[self readValue]];
    case 149: 
      return [YMMFReceiptPigeon fromList:[self readValue]];
    case 150: 
      return [YMMFReporterConfigPigeon fromList:[self readValue]];
    case 151: 
      return [YMMFRevenuePigeon fromList:[self readValue]];
    case 152: 
      return [YMMFStackTraceElementPigeon fromList:[self readValue]];
    case 153: 
      return [YMMFUserProfileAttributePigeon fromList:[self readValue]];
    case 154: 
      return [YMMFUserProfilePigeon fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface YMMFAppMetricaPigeonCodecWriter : FlutterStandardWriter
@end
@implementation YMMFAppMetricaPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[YMMFAdRevenuePigeon class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFAppMetricaConfigPigeon class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFAppMetricaDeferredDeeplinkErrorPigeon class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFAppMetricaDeferredDeeplinkParametersPigeon class]]) {
    [self writeByte:131];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFAppMetricaDeferredDeeplinkPigeon class]]) {
    [self writeByte:132];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFAppMetricaDeviceIdPigeon class]]) {
    [self writeByte:133];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFECommerceAmountPigeon class]]) {
    [self writeByte:134];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFECommerceAmountPigeon class]]) {
    [self writeByte:135];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFECommerceCartItemPigeon class]]) {
    [self writeByte:136];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFECommerceEventPigeon class]]) {
    [self writeByte:137];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFECommerceOrderPigeon class]]) {
    [self writeByte:138];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFECommercePricePigeon class]]) {
    [self writeByte:139];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFECommercePricePigeon class]]) {
    [self writeByte:140];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFECommerceProductPigeon class]]) {
    [self writeByte:141];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFECommerceProductPigeon class]]) {
    [self writeByte:142];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFECommerceReferrerPigeon class]]) {
    [self writeByte:143];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFECommerceScreenPigeon class]]) {
    [self writeByte:144];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFErrorDetailsPigeon class]]) {
    [self writeByte:145];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFErrorDetailsPigeon class]]) {
    [self writeByte:146];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFLocationPigeon class]]) {
    [self writeByte:147];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFPreloadInfoPigeon class]]) {
    [self writeByte:148];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFReceiptPigeon class]]) {
    [self writeByte:149];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFReporterConfigPigeon class]]) {
    [self writeByte:150];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFRevenuePigeon class]]) {
    [self writeByte:151];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFStackTraceElementPigeon class]]) {
    [self writeByte:152];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFUserProfileAttributePigeon class]]) {
    [self writeByte:153];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFUserProfilePigeon class]]) {
    [self writeByte:154];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface YMMFAppMetricaPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation YMMFAppMetricaPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[YMMFAppMetricaPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[YMMFAppMetricaPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *YMMFAppMetricaPigeonGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    YMMFAppMetricaPigeonCodecReaderWriter *readerWriter = [[YMMFAppMetricaPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void YMMFAppMetricaPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<YMMFAppMetricaPigeon> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.activate"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(activateConfig:error:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(activateConfig:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        YMMFAppMetricaConfigPigeon *arg_config = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api activateConfig:arg_config error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.activateReporter"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(activateReporterConfig:error:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(activateReporterConfig:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        YMMFReporterConfigPigeon *arg_config = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api activateReporterConfig:arg_config error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.touchReporter"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(touchReporterApiKey:error:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(touchReporterApiKey:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_apiKey = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api touchReporterApiKey:arg_apiKey error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.getLibraryApiLevel"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getLibraryApiLevelWithError:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(getLibraryApiLevelWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api getLibraryApiLevelWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.getLibraryVersion"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getLibraryVersionWithError:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(getLibraryVersionWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSString *output = [api getLibraryVersionWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.resumeSession"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(resumeSessionWithError:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(resumeSessionWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api resumeSessionWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.pauseSession"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(pauseSessionWithError:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(pauseSessionWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api pauseSessionWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.reportAppOpen"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportAppOpenDeeplink:error:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(reportAppOpenDeeplink:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_deeplink = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api reportAppOpenDeeplink:arg_deeplink error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.reportError"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportErrorError:message:error:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(reportErrorError:message:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        YMMFErrorDetailsPigeon *arg_error = GetNullableObjectAtIndex(args, 0);
        NSString *arg_message = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api reportErrorError:arg_error message:arg_message error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.reportErrorWithGroup"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportErrorWithGroupGroupId:error:message:error:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(reportErrorWithGroupGroupId:error:message:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_groupId = GetNullableObjectAtIndex(args, 0);
        YMMFErrorDetailsPigeon *arg_error = GetNullableObjectAtIndex(args, 1);
        NSString *arg_message = GetNullableObjectAtIndex(args, 2);
        FlutterError *error;
        [api reportErrorWithGroupGroupId:arg_groupId error:arg_error message:arg_message error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.reportUnhandledException"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportUnhandledExceptionError:error:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(reportUnhandledExceptionError:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        YMMFErrorDetailsPigeon *arg_error = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api reportUnhandledExceptionError:arg_error error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.reportEventWithJson"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportEventWithJsonEventName:attributesJson:error:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(reportEventWithJsonEventName:attributesJson:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_eventName = GetNullableObjectAtIndex(args, 0);
        NSString *arg_attributesJson = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api reportEventWithJsonEventName:arg_eventName attributesJson:arg_attributesJson error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.reportEvent"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportEventEventName:error:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(reportEventEventName:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_eventName = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api reportEventEventName:arg_eventName error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.reportReferralUrl"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportReferralUrlReferralUrl:error:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(reportReferralUrlReferralUrl:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_referralUrl = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api reportReferralUrlReferralUrl:arg_referralUrl error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.requestDeferredDeeplink"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(requestDeferredDeeplinkWithCompletion:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(requestDeferredDeeplinkWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api requestDeferredDeeplinkWithCompletion:^(YMMFAppMetricaDeferredDeeplinkPigeon *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.requestDeferredDeeplinkParameters"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(requestDeferredDeeplinkParametersWithCompletion:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(requestDeferredDeeplinkParametersWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api requestDeferredDeeplinkParametersWithCompletion:^(YMMFAppMetricaDeferredDeeplinkParametersPigeon *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.requestAppMetricaDeviceID"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(requestAppMetricaDeviceIDWithCompletion:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(requestAppMetricaDeviceIDWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api requestAppMetricaDeviceIDWithCompletion:^(YMMFAppMetricaDeviceIdPigeon *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.sendEventsBuffer"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(sendEventsBufferWithError:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(sendEventsBufferWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api sendEventsBufferWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.setLocation"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setLocationLocation:error:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(setLocationLocation:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        YMMFLocationPigeon *arg_location = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setLocationLocation:arg_location error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.setLocationTracking"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setLocationTrackingEnabled:error:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(setLocationTrackingEnabled:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_enabled = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setLocationTrackingEnabled:arg_enabled error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.setStatisticsSending"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setStatisticsSendingEnabled:error:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(setStatisticsSendingEnabled:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_enabled = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setStatisticsSendingEnabled:arg_enabled error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.setUserProfileID"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setUserProfileIDUserProfileID:error:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(setUserProfileIDUserProfileID:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_userProfileID = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setUserProfileIDUserProfileID:arg_userProfileID error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.reportUserProfile"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportUserProfileUserProfile:error:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(reportUserProfileUserProfile:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        YMMFUserProfilePigeon *arg_userProfile = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api reportUserProfileUserProfile:arg_userProfile error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.putErrorEnvironmentValue"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(putErrorEnvironmentValueKey:value:error:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(putErrorEnvironmentValueKey:value:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_key = GetNullableObjectAtIndex(args, 0);
        NSString *arg_value = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api putErrorEnvironmentValueKey:arg_key value:arg_value error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.reportRevenue"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportRevenueRevenue:error:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(reportRevenueRevenue:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        YMMFRevenuePigeon *arg_revenue = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api reportRevenueRevenue:arg_revenue error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.reportECommerce"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportECommerceEvent:error:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(reportECommerceEvent:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        YMMFECommerceEventPigeon *arg_event = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api reportECommerceEvent:arg_event error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.handlePluginInitFinished"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(handlePluginInitFinishedWithError:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(handlePluginInitFinishedWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api handlePluginInitFinishedWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.AppMetricaPigeon.reportAdRevenue"
        binaryMessenger:binaryMessenger
        codec:YMMFAppMetricaPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportAdRevenueAdRevenue:error:)], @"YMMFAppMetricaPigeon api (%@) doesn't respond to @selector(reportAdRevenueAdRevenue:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        YMMFAdRevenuePigeon *arg_adRevenue = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api reportAdRevenueAdRevenue:arg_adRevenue error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface YMMFReporterPigeonCodecReader : FlutterStandardReader
@end
@implementation YMMFReporterPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [YMMFAdRevenuePigeon fromList:[self readValue]];
    case 129: 
      return [YMMFECommerceAmountPigeon fromList:[self readValue]];
    case 130: 
      return [YMMFECommerceAmountPigeon fromList:[self readValue]];
    case 131: 
      return [YMMFECommerceCartItemPigeon fromList:[self readValue]];
    case 132: 
      return [YMMFECommerceEventPigeon fromList:[self readValue]];
    case 133: 
      return [YMMFECommerceOrderPigeon fromList:[self readValue]];
    case 134: 
      return [YMMFECommercePricePigeon fromList:[self readValue]];
    case 135: 
      return [YMMFECommercePricePigeon fromList:[self readValue]];
    case 136: 
      return [YMMFECommerceProductPigeon fromList:[self readValue]];
    case 137: 
      return [YMMFECommerceProductPigeon fromList:[self readValue]];
    case 138: 
      return [YMMFECommerceReferrerPigeon fromList:[self readValue]];
    case 139: 
      return [YMMFECommerceScreenPigeon fromList:[self readValue]];
    case 140: 
      return [YMMFErrorDetailsPigeon fromList:[self readValue]];
    case 141: 
      return [YMMFErrorDetailsPigeon fromList:[self readValue]];
    case 142: 
      return [YMMFReceiptPigeon fromList:[self readValue]];
    case 143: 
      return [YMMFRevenuePigeon fromList:[self readValue]];
    case 144: 
      return [YMMFStackTraceElementPigeon fromList:[self readValue]];
    case 145: 
      return [YMMFUserProfileAttributePigeon fromList:[self readValue]];
    case 146: 
      return [YMMFUserProfilePigeon fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface YMMFReporterPigeonCodecWriter : FlutterStandardWriter
@end
@implementation YMMFReporterPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[YMMFAdRevenuePigeon class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFECommerceAmountPigeon class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFECommerceAmountPigeon class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFECommerceCartItemPigeon class]]) {
    [self writeByte:131];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFECommerceEventPigeon class]]) {
    [self writeByte:132];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFECommerceOrderPigeon class]]) {
    [self writeByte:133];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFECommercePricePigeon class]]) {
    [self writeByte:134];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFECommercePricePigeon class]]) {
    [self writeByte:135];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFECommerceProductPigeon class]]) {
    [self writeByte:136];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFECommerceProductPigeon class]]) {
    [self writeByte:137];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFECommerceReferrerPigeon class]]) {
    [self writeByte:138];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFECommerceScreenPigeon class]]) {
    [self writeByte:139];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFErrorDetailsPigeon class]]) {
    [self writeByte:140];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFErrorDetailsPigeon class]]) {
    [self writeByte:141];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFReceiptPigeon class]]) {
    [self writeByte:142];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFRevenuePigeon class]]) {
    [self writeByte:143];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFStackTraceElementPigeon class]]) {
    [self writeByte:144];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFUserProfileAttributePigeon class]]) {
    [self writeByte:145];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[YMMFUserProfilePigeon class]]) {
    [self writeByte:146];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface YMMFReporterPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation YMMFReporterPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[YMMFReporterPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[YMMFReporterPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *YMMFReporterPigeonGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    YMMFReporterPigeonCodecReaderWriter *readerWriter = [[YMMFReporterPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void YMMFReporterPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<YMMFReporterPigeon> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.ReporterPigeon.sendEventsBuffer"
        binaryMessenger:binaryMessenger
        codec:YMMFReporterPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(sendEventsBufferApiKey:error:)], @"YMMFReporterPigeon api (%@) doesn't respond to @selector(sendEventsBufferApiKey:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_apiKey = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api sendEventsBufferApiKey:arg_apiKey error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.ReporterPigeon.reportEvent"
        binaryMessenger:binaryMessenger
        codec:YMMFReporterPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportEventApiKey:eventName:error:)], @"YMMFReporterPigeon api (%@) doesn't respond to @selector(reportEventApiKey:eventName:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_apiKey = GetNullableObjectAtIndex(args, 0);
        NSString *arg_eventName = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api reportEventApiKey:arg_apiKey eventName:arg_eventName error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.ReporterPigeon.reportEventWithJson"
        binaryMessenger:binaryMessenger
        codec:YMMFReporterPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportEventWithJsonApiKey:eventName:attributesJson:error:)], @"YMMFReporterPigeon api (%@) doesn't respond to @selector(reportEventWithJsonApiKey:eventName:attributesJson:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_apiKey = GetNullableObjectAtIndex(args, 0);
        NSString *arg_eventName = GetNullableObjectAtIndex(args, 1);
        NSString *arg_attributesJson = GetNullableObjectAtIndex(args, 2);
        FlutterError *error;
        [api reportEventWithJsonApiKey:arg_apiKey eventName:arg_eventName attributesJson:arg_attributesJson error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.ReporterPigeon.reportError"
        binaryMessenger:binaryMessenger
        codec:YMMFReporterPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportErrorApiKey:error:message:error:)], @"YMMFReporterPigeon api (%@) doesn't respond to @selector(reportErrorApiKey:error:message:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_apiKey = GetNullableObjectAtIndex(args, 0);
        YMMFErrorDetailsPigeon *arg_error = GetNullableObjectAtIndex(args, 1);
        NSString *arg_message = GetNullableObjectAtIndex(args, 2);
        FlutterError *error;
        [api reportErrorApiKey:arg_apiKey error:arg_error message:arg_message error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.ReporterPigeon.reportErrorWithGroup"
        binaryMessenger:binaryMessenger
        codec:YMMFReporterPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportErrorWithGroupApiKey:groupId:error:message:error:)], @"YMMFReporterPigeon api (%@) doesn't respond to @selector(reportErrorWithGroupApiKey:groupId:error:message:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_apiKey = GetNullableObjectAtIndex(args, 0);
        NSString *arg_groupId = GetNullableObjectAtIndex(args, 1);
        YMMFErrorDetailsPigeon *arg_error = GetNullableObjectAtIndex(args, 2);
        NSString *arg_message = GetNullableObjectAtIndex(args, 3);
        FlutterError *error;
        [api reportErrorWithGroupApiKey:arg_apiKey groupId:arg_groupId error:arg_error message:arg_message error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.ReporterPigeon.reportUnhandledException"
        binaryMessenger:binaryMessenger
        codec:YMMFReporterPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportUnhandledExceptionApiKey:error:error:)], @"YMMFReporterPigeon api (%@) doesn't respond to @selector(reportUnhandledExceptionApiKey:error:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_apiKey = GetNullableObjectAtIndex(args, 0);
        YMMFErrorDetailsPigeon *arg_error = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api reportUnhandledExceptionApiKey:arg_apiKey error:arg_error error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.ReporterPigeon.resumeSession"
        binaryMessenger:binaryMessenger
        codec:YMMFReporterPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(resumeSessionApiKey:error:)], @"YMMFReporterPigeon api (%@) doesn't respond to @selector(resumeSessionApiKey:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_apiKey = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api resumeSessionApiKey:arg_apiKey error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.ReporterPigeon.pauseSession"
        binaryMessenger:binaryMessenger
        codec:YMMFReporterPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(pauseSessionApiKey:error:)], @"YMMFReporterPigeon api (%@) doesn't respond to @selector(pauseSessionApiKey:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_apiKey = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api pauseSessionApiKey:arg_apiKey error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.ReporterPigeon.setStatisticsSending"
        binaryMessenger:binaryMessenger
        codec:YMMFReporterPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setStatisticsSendingApiKey:enabled:error:)], @"YMMFReporterPigeon api (%@) doesn't respond to @selector(setStatisticsSendingApiKey:enabled:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_apiKey = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_enabled = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api setStatisticsSendingApiKey:arg_apiKey enabled:arg_enabled error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.ReporterPigeon.setUserProfileID"
        binaryMessenger:binaryMessenger
        codec:YMMFReporterPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setUserProfileIDApiKey:userProfileID:error:)], @"YMMFReporterPigeon api (%@) doesn't respond to @selector(setUserProfileIDApiKey:userProfileID:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_apiKey = GetNullableObjectAtIndex(args, 0);
        NSString *arg_userProfileID = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api setUserProfileIDApiKey:arg_apiKey userProfileID:arg_userProfileID error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.ReporterPigeon.reportUserProfile"
        binaryMessenger:binaryMessenger
        codec:YMMFReporterPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportUserProfileApiKey:userProfile:error:)], @"YMMFReporterPigeon api (%@) doesn't respond to @selector(reportUserProfileApiKey:userProfile:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_apiKey = GetNullableObjectAtIndex(args, 0);
        YMMFUserProfilePigeon *arg_userProfile = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api reportUserProfileApiKey:arg_apiKey userProfile:arg_userProfile error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.ReporterPigeon.reportRevenue"
        binaryMessenger:binaryMessenger
        codec:YMMFReporterPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportRevenueApiKey:revenue:error:)], @"YMMFReporterPigeon api (%@) doesn't respond to @selector(reportRevenueApiKey:revenue:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_apiKey = GetNullableObjectAtIndex(args, 0);
        YMMFRevenuePigeon *arg_revenue = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api reportRevenueApiKey:arg_apiKey revenue:arg_revenue error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.ReporterPigeon.reportECommerce"
        binaryMessenger:binaryMessenger
        codec:YMMFReporterPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportECommerceApiKey:event:error:)], @"YMMFReporterPigeon api (%@) doesn't respond to @selector(reportECommerceApiKey:event:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_apiKey = GetNullableObjectAtIndex(args, 0);
        YMMFECommerceEventPigeon *arg_event = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api reportECommerceApiKey:arg_apiKey event:arg_event error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.ReporterPigeon.reportAdRevenue"
        binaryMessenger:binaryMessenger
        codec:YMMFReporterPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportAdRevenueApiKey:adRevenue:error:)], @"YMMFReporterPigeon api (%@) doesn't respond to @selector(reportAdRevenueApiKey:adRevenue:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_apiKey = GetNullableObjectAtIndex(args, 0);
        YMMFAdRevenuePigeon *arg_adRevenue = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api reportAdRevenueApiKey:arg_apiKey adRevenue:arg_adRevenue error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
NSObject<FlutterMessageCodec> *YMMFInitialDeepLinkHolderPigeonGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  sSharedObject = [FlutterStandardMessageCodec sharedInstance];
  return sSharedObject;
}

void YMMFInitialDeepLinkHolderPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<YMMFInitialDeepLinkHolderPigeon> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.InitialDeepLinkHolderPigeon.getInitialDeeplink"
        binaryMessenger:binaryMessenger
        codec:YMMFInitialDeepLinkHolderPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getInitialDeeplinkWithError:)], @"YMMFInitialDeepLinkHolderPigeon api (%@) doesn't respond to @selector(getInitialDeeplinkWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSString *output = [api getInitialDeeplinkWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
